### ISSUE TITLE
Don't work on this website: https://irisbuddies.blogspot.com/2016/03/how-to-port-philzctrcwmtwrp-recovery-to.html

### ISSUE THREAD

**Issue by mikhoul** [sutuboss/Past-Pro#1]
Don't work on this website: https://irisbuddies.blogspot.com/2016/03/how-to-port-philzctrcwmtwrp-recovery-to.html

Regards :octocat:

**Comment by sutuboss** [comment]
can you be more specific about what is not working ? I have updated the extension and all the functionalities like copy , paste , select text , right click are working fine . Please use the Updated version .

**Comment by mikhoul** [comment]
Thanks it work with the new version :+1:
